export const SET_WANTED_MOVIES = 'SET_WANTED_MOVIES'

export const SET_WATCHED_MOVIES = 'SET_WATCHEDED_MOVIES'

export const SET_CELEBRITIES = 'SET_CELEBRITIES'

export const SAVE_SEARCHHISTORY = 'SAVE_SEARCHHISTORY'

export const DELETE_SEARCHHISTORY = 'DELETE_SEARCHHISTORY'

export const CLEAR_SEARCHHISTORY = 'CLEAR_SEARCHHISTORY'
